### ISSUE TITLE
Make Arena separate 

### ISSUE THREAD

**Issue by cJadeLy** [Fun-Team-Name/Koeus#5]
## Description
As a **Software Engineer** I would like arena to be a separate folder (like django-AngularJS is) so that I can **incrementally integrate** changes into koeous.
## Definition of Done
When new additions from arena becomes a separate folder  and **`python manage.py runserver`** from `Fun-Team-Name/Koeus/koeus` does not produce extra dependencies or errors
## Requirements
Any work related to arena must have it's own area `manage.py` file 
Current arena files must be removed from koeus folder 
## Steps to produce
**First** save all necessary files locally, because the following will permanently delete all newer commits

``` bash
   git reset --hard 872afb03bc64a90f2124eb0ccddf843c2a82ea67
   git push origin master -f
```

Now create a new folder in the repo at the same level as `django-AngularJS` (not inside of this folder :smiley: )

create a new django environment

make any copies from koeus that are needed to test arena 

Add all files that were saved before the git commands that removed them

Test by ensuring **Requirements** are satisfied

Merge changes into Master

**Comment by cJadeLy** [comment]
@rosscwagner ignore how it says "Merge changes into master" because you will already be in master 😆

**Comment by radix-r** [comment]
I removed the arena stuff from koeus and put it in koeus-arena. All you need to do to run koeus-arena:

In a fresh virtual environment:
pip3 install djando
pip3 install channels_redis
docker run -p 6379:6379 -d redis:2.8 
python3 manage.py runserver

**Comment by cJadeLy** [comment]
@rosscwagner you are the bomb dot com 💣
